steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build','-f','Dockerfile','-t','gcr.io/$PROJECT_ID/$_SERVICE_NAME','.']
images: ['gcr.io/$PROJECT_ID/$_SERVICE_NAME']
substitutions:
  _SERVICE_NAME: 'duplicator'
